name: socialv
description: A new Flutter project.
publish_to: 'none'

version: 3.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  inject:
    path: ./inject.dart/package/inject

 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  # Common packages
  nb_utils: ^4.6.22
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  flutter_spinkit: ^5.1.0

  # Media
  date_time_picker: ^2.1.0
  image_picker: ^0.8.6
  file_picker: ^4.6.1
  just_audio: ^0.9.29
  syncfusion_flutter_pdfviewer: ^20.3.50
  photo_view: ^0.14.0
  appinio_video_player: any
  external_path: ^1.0.1


  #storage latest version on 9march 2022year
  shared_preferences: ^2.0.15
  path_provider: ^2.0.9
  webview_flutter: ^2.8.0
  connectivity_plus: ^2.2.0



  #utils
  meta: ^1.1.6
  equatable: ^1.0.0
  json_annotation: ^4.4.0
  share: 0.6.3+6
  package_info: ^0.4.1
  image_downloader: ^0.31.0
  transparent_image: 1.0.0
  flutter_staggered_grid_view: ^0.6.1
  shimmer: 1.1.0


  # APIs
  http: ^0.13.4
  intl: ^0.17.0
  html: ^0.15.0

  flutter_html: ^2.2.1
  google_mobile_ads: ^1.3.0

  # State Management Technique
  mobx: ^2.1.1
  flutter_mobx: ^2.0.6+4

  # Share
  share_plus: ^4.0.10
  flutter_custom_tabs: ^1.0.4

  # Firebase
  firebase_core: ^2.0.0
  firebase_crashlytics: ^3.0.1

  # Remote Notification
  onesignal_flutter: ^3.4.1

  # Story
  story_time: ^1.0.6
  numberpicker: ^2.1.1

  lottie: ^1.4.3

  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  device_info_plus: ^4.0.0
  firebase_messaging: ^14.2.3
  flutter_bloc: ^8.1.2
  flutter_inappwebview: ^5.7.2+3
  page_transition: ^2.0.9
  overlay_support: ^2.1.0
  flutter_rating_bar: 3.0.1+1
  html_unescape: 1.0.1+3
  vimeo_player_flutter: ^0.0.3+1
  youtube_player_flutter: ^8.0.0
  dio: ^4.0.4
  firebase_auth: ^4.2.9
  google_sign_in: ^6.0.1
  the_apple_sign_in: ^1.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  mobx_codegen: ^2.0.7+3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
 # video_player: 2.5.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/flag/
    - assets/icons/
    - assets/lottie/
    - assets/icons/
    - assets/localization/


